#include "stdafx.h"
#include "AIHeroClient.h"

#pragma region CHAMPION DICTIONARY
const std::map<std::string, EChampion::EChampion> AIHeroClient::ChampionMap =
{
	std::pair<std::string, EChampion::EChampion>("Aatrox", EChampion::Aatrox),
	std::pair<std::string, EChampion::EChampion>("Ahri", EChampion::Ahri),
	std::pair<std::string, EChampion::EChampion>("Akali", EChampion::Akali),
	std::pair<std::string, EChampion::EChampion>("Alistar", EChampion::Alistar),
	std::pair<std::string, EChampion::EChampion>("Amumu", EChampion::Amumu),
	std::pair<std::string, EChampion::EChampion>("Anivia", EChampion::Anivia),
	std::pair<std::string, EChampion::EChampion>("Annie", EChampion::Annie),
	std::pair<std::string, EChampion::EChampion>("Ashe", EChampion::Ashe),
	std::pair<std::string, EChampion::EChampion>("Azir", EChampion::Azir),
	std::pair<std::string, EChampion::EChampion>("Bard", EChampion::Bard),
	std::pair<std::string, EChampion::EChampion>("Blitzcrank", EChampion::Blitzcrank),
	std::pair<std::string, EChampion::EChampion>("Brand", EChampion::Brand),
	std::pair<std::string, EChampion::EChampion>("Braum", EChampion::Braum),
	std::pair<std::string, EChampion::EChampion>("Caitlyn", EChampion::Caitlyn),
	std::pair<std::string, EChampion::EChampion>("Cassiopeia", EChampion::Cassiopeia),
	std::pair<std::string, EChampion::EChampion>("Chogath", EChampion::Chogath),
	std::pair<std::string, EChampion::EChampion>("Corki", EChampion::Corki),
	std::pair<std::string, EChampion::EChampion>("Darius", EChampion::Darius),
	std::pair<std::string, EChampion::EChampion>("Diana", EChampion::Diana),
	std::pair<std::string, EChampion::EChampion>("DrMundo", EChampion::DrMundo),
	std::pair<std::string, EChampion::EChampion>("Draven", EChampion::Draven),
	std::pair<std::string, EChampion::EChampion>("Ekko", EChampion::Ekko),
	std::pair<std::string, EChampion::EChampion>("Elise", EChampion::Elise),
	std::pair<std::string, EChampion::EChampion>("Evelynn", EChampion::Evelynn),
	std::pair<std::string, EChampion::EChampion>("Ezreal", EChampion::Ezreal),
	std::pair<std::string, EChampion::EChampion>("FiddleSticks", EChampion::FiddleSticks),
	std::pair<std::string, EChampion::EChampion>("Fiora", EChampion::Fiora),
	std::pair<std::string, EChampion::EChampion>("Fizz", EChampion::Fizz),
	std::pair<std::string, EChampion::EChampion>("Galio", EChampion::Galio),
	std::pair<std::string, EChampion::EChampion>("Gangplank", EChampion::Gangplank),
	std::pair<std::string, EChampion::EChampion>("Garen", EChampion::Garen),
	std::pair<std::string, EChampion::EChampion>("Gnar", EChampion::Gnar),
	std::pair<std::string, EChampion::EChampion>("Gragas", EChampion::Gragas),
	std::pair<std::string, EChampion::EChampion>("Graves", EChampion::Graves),
	std::pair<std::string, EChampion::EChampion>("Hecarim", EChampion::Hecarim),
	std::pair<std::string, EChampion::EChampion>("Heimerdinger", EChampion::Heimerdinger),
	std::pair<std::string, EChampion::EChampion>("Illaoi", EChampion::Illaoi),
	std::pair<std::string, EChampion::EChampion>("Irelia", EChampion::Irelia),
	std::pair<std::string, EChampion::EChampion>("Janna", EChampion::Janna),
	std::pair<std::string, EChampion::EChampion>("JarvanIV", EChampion::JarvanIV),
	std::pair<std::string, EChampion::EChampion>("Jax", EChampion::Jax),
	std::pair<std::string, EChampion::EChampion>("Jayce", EChampion::Jayce),
	std::pair<std::string, EChampion::EChampion>("Jhin", EChampion::Jhin),
	std::pair<std::string, EChampion::EChampion>("Jinx", EChampion::Jinx),
	std::pair<std::string, EChampion::EChampion>("Kalista", EChampion::Kalista),
	std::pair<std::string, EChampion::EChampion>("Karma", EChampion::Karma),
	std::pair<std::string, EChampion::EChampion>("Karthus", EChampion::Karthus),
	std::pair<std::string, EChampion::EChampion>("Kassadin", EChampion::Kassadin),
	std::pair<std::string, EChampion::EChampion>("Katarina", EChampion::Katarina),
	std::pair<std::string, EChampion::EChampion>("Kayle", EChampion::Kayle),
	std::pair<std::string, EChampion::EChampion>("Kayn", EChampion::Kayn),
	std::pair<std::string, EChampion::EChampion>("Kennen", EChampion::Kennen),
	std::pair<std::string, EChampion::EChampion>("Khazix", EChampion::Khazix),
	std::pair<std::string, EChampion::EChampion>("Kindred", EChampion::Kindred),
	std::pair<std::string, EChampion::EChampion>("Kled", EChampion::Kled),
	std::pair<std::string, EChampion::EChampion>("KogMaw", EChampion::KogMaw),
	std::pair<std::string, EChampion::EChampion>("Leblanc", EChampion::Leblanc),
	std::pair<std::string, EChampion::EChampion>("LeeSin", EChampion::LeeSin),
	std::pair<std::string, EChampion::EChampion>("Leona", EChampion::Leona),
	std::pair<std::string, EChampion::EChampion>("Lissandra", EChampion::Lissandra),
	std::pair<std::string, EChampion::EChampion>("Lucian", EChampion::Lucian),
	std::pair<std::string, EChampion::EChampion>("Lulu", EChampion::Lulu),
	std::pair<std::string, EChampion::EChampion>("Lux", EChampion::Lux),
	std::pair<std::string, EChampion::EChampion>("Malphite", EChampion::Malphite),
	std::pair<std::string, EChampion::EChampion>("Malzahar", EChampion::Malzahar),
	std::pair<std::string, EChampion::EChampion>("Maokai", EChampion::Maokai),
	std::pair<std::string, EChampion::EChampion>("MasterYi", EChampion::MasterYi),
	std::pair<std::string, EChampion::EChampion>("MissFortune", EChampion::MissFortune),
	std::pair<std::string, EChampion::EChampion>("Mordekaiser", EChampion::Mordekaiser),
	std::pair<std::string, EChampion::EChampion>("Morgana", EChampion::Morgana),
	std::pair<std::string, EChampion::EChampion>("Nami", EChampion::Nami),
	std::pair<std::string, EChampion::EChampion>("Nasus", EChampion::Nasus),
	std::pair<std::string, EChampion::EChampion>("Nautilus", EChampion::Nautilus),
	std::pair<std::string, EChampion::EChampion>("Nidalee", EChampion::Nidalee),
	std::pair<std::string, EChampion::EChampion>("Nocturne", EChampion::Nocturne),
	std::pair<std::string, EChampion::EChampion>("Nunu", EChampion::Nunu),
	std::pair<std::string, EChampion::EChampion>("Olaf", EChampion::Olaf),
	std::pair<std::string, EChampion::EChampion>("Orianna", EChampion::Orianna),
	std::pair<std::string, EChampion::EChampion>("Pantheon", EChampion::Pantheon),
	std::pair<std::string, EChampion::EChampion>("Poppy", EChampion::Poppy),
	std::pair<std::string, EChampion::EChampion>("Quinn", EChampion::Quinn),
	std::pair<std::string, EChampion::EChampion>("Rammus", EChampion::Rammus),
	std::pair<std::string, EChampion::EChampion>("RekSai", EChampion::RekSai),
	std::pair<std::string, EChampion::EChampion>("Renekton", EChampion::Renekton),
	std::pair<std::string, EChampion::EChampion>("Rengar", EChampion::Rengar),
	std::pair<std::string, EChampion::EChampion>("Riven", EChampion::Riven),
	std::pair<std::string, EChampion::EChampion>("Rumble", EChampion::Rumble),
	std::pair<std::string, EChampion::EChampion>("Ryze", EChampion::Ryze),
	std::pair<std::string, EChampion::EChampion>("Sejuani", EChampion::Sejuani),
	std::pair<std::string, EChampion::EChampion>("Shaco", EChampion::Shaco),
	std::pair<std::string, EChampion::EChampion>("Shen", EChampion::Shen),
	std::pair<std::string, EChampion::EChampion>("Shyvana", EChampion::Shyvana),
	std::pair<std::string, EChampion::EChampion>("Singed", EChampion::Singed),
	std::pair<std::string, EChampion::EChampion>("Sion", EChampion::Sion),
	std::pair<std::string, EChampion::EChampion>("Sivir", EChampion::Sivir),
	std::pair<std::string, EChampion::EChampion>("Skarner", EChampion::Skarner),
	std::pair<std::string, EChampion::EChampion>("Sona", EChampion::Sona),
	std::pair<std::string, EChampion::EChampion>("Soraka", EChampion::Soraka),
	std::pair<std::string, EChampion::EChampion>("Swain", EChampion::Swain),
	std::pair<std::string, EChampion::EChampion>("Syndra", EChampion::Syndra),
	std::pair<std::string, EChampion::EChampion>("TahmKench", EChampion::TahmKench),
	std::pair<std::string, EChampion::EChampion>("Talon", EChampion::Talon),
	std::pair<std::string, EChampion::EChampion>("Taric", EChampion::Taric),
	std::pair<std::string, EChampion::EChampion>("Teemo", EChampion::Teemo),
	std::pair<std::string, EChampion::EChampion>("Thresh", EChampion::Thresh),
	std::pair<std::string, EChampion::EChampion>("Tristana", EChampion::Tristana),
	std::pair<std::string, EChampion::EChampion>("Trundle", EChampion::Trundle),
	std::pair<std::string, EChampion::EChampion>("Tryndamere", EChampion::Tryndamere),
	std::pair<std::string, EChampion::EChampion>("TwistedFate", EChampion::TwistedFate),
	std::pair<std::string, EChampion::EChampion>("Twitch", EChampion::Twitch),
	std::pair<std::string, EChampion::EChampion>("Udyr", EChampion::Udyr),
	std::pair<std::string, EChampion::EChampion>("Urgot", EChampion::Urgot),
	std::pair<std::string, EChampion::EChampion>("Varus", EChampion::Varus),
	std::pair<std::string, EChampion::EChampion>("Vayne", EChampion::Vayne),
	std::pair<std::string, EChampion::EChampion>("Veigar", EChampion::Veigar),
	std::pair<std::string, EChampion::EChampion>("Velkoz", EChampion::Velkoz),
	std::pair<std::string, EChampion::EChampion>("Vi", EChampion::Vi),
	std::pair<std::string, EChampion::EChampion>("Viktor", EChampion::Viktor),
	std::pair<std::string, EChampion::EChampion>("Vladimir", EChampion::Vladimir),
	std::pair<std::string, EChampion::EChampion>("Volibear", EChampion::Volibear),
	std::pair<std::string, EChampion::EChampion>("Warwick", EChampion::Warwick),
	std::pair<std::string, EChampion::EChampion>("MonkeyKing", EChampion::MonkeyKing),
	std::pair<std::string, EChampion::EChampion>("Xerath", EChampion::Xerath),
	std::pair<std::string, EChampion::EChampion>("XinZhao", EChampion::XinZhao),
	std::pair<std::string, EChampion::EChampion>("Yasuo", EChampion::Yasuo),
	std::pair<std::string, EChampion::EChampion>("Yorick", EChampion::Yorick),
	std::pair<std::string, EChampion::EChampion>("Zac", EChampion::Zac),
	std::pair<std::string, EChampion::EChampion>("Zed", EChampion::Zed),
	std::pair<std::string, EChampion::EChampion>("Ziggs", EChampion::Ziggs),
	std::pair<std::string, EChampion::EChampion>("Zilean", EChampion::Zilean),
	std::pair<std::string, EChampion::EChampion>("Zyra", EChampion::Zyra),
		//New Champions
	std::pair<std::string, EChampion::EChampion>("Pyke", EChampion::Pyke),
	std::pair<std::string, EChampion::EChampion>("KaiSa", EChampion::KaiSa),
	std::pair<std::string, EChampion::EChampion>("Zoe", EChampion::Zoe),
	std::pair<std::string, EChampion::EChampion>("Ornn", EChampion::Ornn),
	std::pair<std::string, EChampion::EChampion>("Rakan", EChampion::Rakan),
	std::pair<std::string, EChampion::EChampion>("Xayah", EChampion::Xayah),
	std::pair<std::string, EChampion::EChampion>("Camille", EChampion::Camille),
	std::pair<std::string, EChampion::EChampion>("Ivern", EChampion::Ivern),
	std::pair<std::string, EChampion::EChampion>("Taliyah", EChampion::Taliyah),
	std::pair<std::string, EChampion::EChampion>("AurelionSol", EChampion::AurelionSol),
};
#pragma endregion // ChampionMap

EChampion::EChampion AIHeroClient::GetHero()
{
	auto search = ChampionMap.find(GetAIName());
	if (search != ChampionMap.end())
		return search->second;
	return EChampion::Unknown;
}
