#include "stdafx.h"
#include "AIHeroClient.h"

#pragma region CHAMPION DICTIONARY
const std::map<std::string, Champion::Champion> AIHeroClient::ChampionMap =
{
	std::pair<std::string, Champion::Champion>("Aatrox", Champion::Aatrox),
	std::pair<std::string, Champion::Champion>("Ahri", Champion::Ahri),
	std::pair<std::string, Champion::Champion>("Akali", Champion::Akali),
	std::pair<std::string, Champion::Champion>("Alistar", Champion::Alistar),
	std::pair<std::string, Champion::Champion>("Amumu", Champion::Amumu),
	std::pair<std::string, Champion::Champion>("Anivia", Champion::Anivia),
	std::pair<std::string, Champion::Champion>("Annie", Champion::Annie),
	std::pair<std::string, Champion::Champion>("Ashe", Champion::Ashe),
	std::pair<std::string, Champion::Champion>("Azir", Champion::Azir),
	std::pair<std::string, Champion::Champion>("Bard", Champion::Bard),
	std::pair<std::string, Champion::Champion>("Blitzcrank", Champion::Blitzcrank),
	std::pair<std::string, Champion::Champion>("Brand", Champion::Brand),
	std::pair<std::string, Champion::Champion>("Braum", Champion::Braum),
	std::pair<std::string, Champion::Champion>("Caitlyn", Champion::Caitlyn),
	std::pair<std::string, Champion::Champion>("Cassiopeia", Champion::Cassiopeia),
	std::pair<std::string, Champion::Champion>("Chogath", Champion::Chogath),
	std::pair<std::string, Champion::Champion>("Corki", Champion::Corki),
	std::pair<std::string, Champion::Champion>("Darius", Champion::Darius),
	std::pair<std::string, Champion::Champion>("Diana", Champion::Diana),
	std::pair<std::string, Champion::Champion>("DrMundo", Champion::DrMundo),
	std::pair<std::string, Champion::Champion>("Draven", Champion::Draven),
	std::pair<std::string, Champion::Champion>("Ekko", Champion::Ekko),
	std::pair<std::string, Champion::Champion>("Elise", Champion::Elise),
	std::pair<std::string, Champion::Champion>("Evelynn", Champion::Evelynn),
	std::pair<std::string, Champion::Champion>("Ezreal", Champion::Ezreal),
	std::pair<std::string, Champion::Champion>("FiddleSticks", Champion::FiddleSticks),
	std::pair<std::string, Champion::Champion>("Fiora", Champion::Fiora),
	std::pair<std::string, Champion::Champion>("Fizz", Champion::Fizz),
	std::pair<std::string, Champion::Champion>("Galio", Champion::Galio),
	std::pair<std::string, Champion::Champion>("Gangplank", Champion::Gangplank),
	std::pair<std::string, Champion::Champion>("Garen", Champion::Garen),
	std::pair<std::string, Champion::Champion>("Gnar", Champion::Gnar),
	std::pair<std::string, Champion::Champion>("Gragas", Champion::Gragas),
	std::pair<std::string, Champion::Champion>("Graves", Champion::Graves),
	std::pair<std::string, Champion::Champion>("Hecarim", Champion::Hecarim),
	std::pair<std::string, Champion::Champion>("Heimerdinger", Champion::Heimerdinger),
	std::pair<std::string, Champion::Champion>("Illaoi", Champion::Illaoi),
	std::pair<std::string, Champion::Champion>("Irelia", Champion::Irelia),
	std::pair<std::string, Champion::Champion>("Janna", Champion::Janna),
	std::pair<std::string, Champion::Champion>("JarvanIV", Champion::JarvanIV),
	std::pair<std::string, Champion::Champion>("Jax", Champion::Jax),
	std::pair<std::string, Champion::Champion>("Jayce", Champion::Jayce),
	std::pair<std::string, Champion::Champion>("Jhin", Champion::Jhin),
	std::pair<std::string, Champion::Champion>("Jinx", Champion::Jinx),
	std::pair<std::string, Champion::Champion>("Kalista", Champion::Kalista),
	std::pair<std::string, Champion::Champion>("Karma", Champion::Karma),
	std::pair<std::string, Champion::Champion>("Karthus", Champion::Karthus),
	std::pair<std::string, Champion::Champion>("Kassadin", Champion::Kassadin),
	std::pair<std::string, Champion::Champion>("Katarina", Champion::Katarina),
	std::pair<std::string, Champion::Champion>("Kayle", Champion::Kayle),
	std::pair<std::string, Champion::Champion>("Kayn", Champion::Kayn),
	std::pair<std::string, Champion::Champion>("Kennen", Champion::Kennen),
	std::pair<std::string, Champion::Champion>("Khazix", Champion::Khazix),
	std::pair<std::string, Champion::Champion>("Kindred", Champion::Kindred),
	std::pair<std::string, Champion::Champion>("Kled", Champion::Kled),
	std::pair<std::string, Champion::Champion>("KogMaw", Champion::KogMaw),
	std::pair<std::string, Champion::Champion>("Leblanc", Champion::Leblanc),
	std::pair<std::string, Champion::Champion>("LeeSin", Champion::LeeSin),
	std::pair<std::string, Champion::Champion>("Leona", Champion::Leona),
	std::pair<std::string, Champion::Champion>("Lissandra", Champion::Lissandra),
	std::pair<std::string, Champion::Champion>("Lucian", Champion::Lucian),
	std::pair<std::string, Champion::Champion>("Lulu", Champion::Lulu),
	std::pair<std::string, Champion::Champion>("Lux", Champion::Lux),
	std::pair<std::string, Champion::Champion>("Malphite", Champion::Malphite),
	std::pair<std::string, Champion::Champion>("Malzahar", Champion::Malzahar),
	std::pair<std::string, Champion::Champion>("Maokai", Champion::Maokai),
	std::pair<std::string, Champion::Champion>("MasterYi", Champion::MasterYi),
	std::pair<std::string, Champion::Champion>("MissFortune", Champion::MissFortune),
	std::pair<std::string, Champion::Champion>("Mordekaiser", Champion::Mordekaiser),
	std::pair<std::string, Champion::Champion>("Morgana", Champion::Morgana),
	std::pair<std::string, Champion::Champion>("Nami", Champion::Nami),
	std::pair<std::string, Champion::Champion>("Nasus", Champion::Nasus),
	std::pair<std::string, Champion::Champion>("Nautilus", Champion::Nautilus),
	std::pair<std::string, Champion::Champion>("Nidalee", Champion::Nidalee),
	std::pair<std::string, Champion::Champion>("Nocturne", Champion::Nocturne),
	std::pair<std::string, Champion::Champion>("Nunu", Champion::Nunu),
	std::pair<std::string, Champion::Champion>("Olaf", Champion::Olaf),
	std::pair<std::string, Champion::Champion>("Orianna", Champion::Orianna),
	std::pair<std::string, Champion::Champion>("Pantheon", Champion::Pantheon),
	std::pair<std::string, Champion::Champion>("Poppy", Champion::Poppy),
	std::pair<std::string, Champion::Champion>("Quinn", Champion::Quinn),
	std::pair<std::string, Champion::Champion>("Rammus", Champion::Rammus),
	std::pair<std::string, Champion::Champion>("RekSai", Champion::RekSai),
	std::pair<std::string, Champion::Champion>("Renekton", Champion::Renekton),
	std::pair<std::string, Champion::Champion>("Rengar", Champion::Rengar),
	std::pair<std::string, Champion::Champion>("Riven", Champion::Riven),
	std::pair<std::string, Champion::Champion>("Rumble", Champion::Rumble),
	std::pair<std::string, Champion::Champion>("Ryze", Champion::Ryze),
	std::pair<std::string, Champion::Champion>("Sejuani", Champion::Sejuani),
	std::pair<std::string, Champion::Champion>("Shaco", Champion::Shaco),
	std::pair<std::string, Champion::Champion>("Shen", Champion::Shen),
	std::pair<std::string, Champion::Champion>("Shyvana", Champion::Shyvana),
	std::pair<std::string, Champion::Champion>("Singed", Champion::Singed),
	std::pair<std::string, Champion::Champion>("Sion", Champion::Sion),
	std::pair<std::string, Champion::Champion>("Sivir", Champion::Sivir),
	std::pair<std::string, Champion::Champion>("Skarner", Champion::Skarner),
	std::pair<std::string, Champion::Champion>("Sona", Champion::Sona),
	std::pair<std::string, Champion::Champion>("Soraka", Champion::Soraka),
	std::pair<std::string, Champion::Champion>("Swain", Champion::Swain),
	std::pair<std::string, Champion::Champion>("Syndra", Champion::Syndra),
	std::pair<std::string, Champion::Champion>("TahmKench", Champion::TahmKench),
	std::pair<std::string, Champion::Champion>("Talon", Champion::Talon),
	std::pair<std::string, Champion::Champion>("Taric", Champion::Taric),
	std::pair<std::string, Champion::Champion>("Teemo", Champion::Teemo),
	std::pair<std::string, Champion::Champion>("Thresh", Champion::Thresh),
	std::pair<std::string, Champion::Champion>("Tristana", Champion::Tristana),
	std::pair<std::string, Champion::Champion>("Trundle", Champion::Trundle),
	std::pair<std::string, Champion::Champion>("Tryndamere", Champion::Tryndamere),
	std::pair<std::string, Champion::Champion>("TwistedFate", Champion::TwistedFate),
	std::pair<std::string, Champion::Champion>("Twitch", Champion::Twitch),
	std::pair<std::string, Champion::Champion>("Udyr", Champion::Udyr),
	std::pair<std::string, Champion::Champion>("Urgot", Champion::Urgot),
	std::pair<std::string, Champion::Champion>("Varus", Champion::Varus),
	std::pair<std::string, Champion::Champion>("Vayne", Champion::Vayne),
	std::pair<std::string, Champion::Champion>("Veigar", Champion::Veigar),
	std::pair<std::string, Champion::Champion>("Velkoz", Champion::Velkoz),
	std::pair<std::string, Champion::Champion>("Vi", Champion::Vi),
	std::pair<std::string, Champion::Champion>("Viktor", Champion::Viktor),
	std::pair<std::string, Champion::Champion>("Vladimir", Champion::Vladimir),
	std::pair<std::string, Champion::Champion>("Volibear", Champion::Volibear),
	std::pair<std::string, Champion::Champion>("Warwick", Champion::Warwick),
	std::pair<std::string, Champion::Champion>("MonkeyKing", Champion::MonkeyKing),
	std::pair<std::string, Champion::Champion>("Xerath", Champion::Xerath),
	std::pair<std::string, Champion::Champion>("XinZhao", Champion::XinZhao),
	std::pair<std::string, Champion::Champion>("Yasuo", Champion::Yasuo),
	std::pair<std::string, Champion::Champion>("Yorick", Champion::Yorick),
	std::pair<std::string, Champion::Champion>("Zac", Champion::Zac),
	std::pair<std::string, Champion::Champion>("Zed", Champion::Zed),
	std::pair<std::string, Champion::Champion>("Ziggs", Champion::Ziggs),
	std::pair<std::string, Champion::Champion>("Zilean", Champion::Zilean),
	std::pair<std::string, Champion::Champion>("Zyra", Champion::Zyra),
		//New Champions
	std::pair<std::string, Champion::Champion>("Pyke", Champion::Pyke),
	std::pair<std::string, Champion::Champion>("KaiSa", Champion::KaiSa),
	std::pair<std::string, Champion::Champion>("Zoe", Champion::Zoe),
	std::pair<std::string, Champion::Champion>("Ornn", Champion::Ornn),
	std::pair<std::string, Champion::Champion>("Rakan", Champion::Rakan),
	std::pair<std::string, Champion::Champion>("Xayah", Champion::Xayah),
	std::pair<std::string, Champion::Champion>("Camille", Champion::Camille),
	std::pair<std::string, Champion::Champion>("Ivern", Champion::Ivern),
	std::pair<std::string, Champion::Champion>("Taliyah", Champion::Taliyah),
	std::pair<std::string, Champion::Champion>("AurelionSol", Champion::AurelionSol),
};
#pragma endregion // ChampionMap

Champion::Champion AIHeroClient::GetHero()
{
	auto search = ChampionMap.find(GetAIName());
	if (search != ChampionMap.end())
		return search->second;
	return Champion::Unknown;
}
